name: Update GitHub Stats

on:
  schedule:
    - cron: '0 0 * * *'  # Executa todo dia à meia-noite UTC
  workflow_dispatch:      # Permite execução manual

permissions:
  contents: write  # Permite escrever no repositório

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Configurar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Instalar dependências
        run: |
          pip install requests lxml python-dateutil
      
      - name: Rodar o script
        env:
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          USER_NAME: ${{ secrets.USER_NAME }}
        run: |
          mkdir -p cache
          python today.py
      
      - name: Commit e push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add *.svg cache/*.txt
          git commit -m "update: GitHub stats via GitHub Actions" || echo "Nada a commitar"
          git push
